-- Consolidated in 20260623183000_fix_auth_profile_and_services_is_active.sql.
--
-- This migration used to run before the tables it referenced and also created
-- the policy "Público pode buscar pacientes" twice. It remains as a no-op so
-- existing migration history keeps the same version.
